"""distances columns

Revision ID: 693c54cb082a
Revises: be2f8d2c9992
Create Date: 2025-07-27 18:36:33.686713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693c54cb082a'
down_revision: Union[str, None] = 'be2f8d2c9992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('duration_to_leonardo_transit', sa.Float(), nullable=True))
    op.add_column('rentals', sa.Column('duration_to_bovisa_transit', sa.Float(), nullable=True))
    op.add_column('rentals', sa.Column('duration_to_leonardo_walking', sa.Float(), nullable=True))
    op.add_column('rentals', sa.Column('duration_to_bovisa_walking', sa.Float(), nullable=True))
    op.create_index(op.f('ix_rentals_duration_to_bovisa_transit'), 'rentals', ['duration_to_bovisa_transit'], unique=False)
    op.create_index(op.f('ix_rentals_duration_to_bovisa_walking'), 'rentals', ['duration_to_bovisa_walking'], unique=False)
    op.create_index(op.f('ix_rentals_duration_to_leonardo_transit'), 'rentals', ['duration_to_leonardo_transit'], unique=False)
    op.create_index(op.f('ix_rentals_duration_to_leonardo_walking'), 'rentals', ['duration_to_leonardo_walking'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_duration_to_leonardo_walking'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_duration_to_leonardo_transit'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_duration_to_bovisa_walking'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_duration_to_bovisa_transit'), table_name='rentals')
    op.drop_column('rentals', 'duration_to_bovisa_walking')
    op.drop_column('rentals', 'duration_to_leonardo_walking')
    op.drop_column('rentals', 'duration_to_bovisa_transit')
    op.drop_column('rentals', 'duration_to_leonardo_transit')
    # ### end Alembic commands ###
