"""Add extra expenses fields to rentals

Revision ID: be2f8d2c9992
Revises: 
Create Date: 2025-07-23 17:19:07.876398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2f8d2c9992'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column(
        'has_extra_expenses', sa.Boolean(), nullable=True))
    op.add_column('rentals', sa.Column(
        'extra_expenses_details', sa.String(), nullable=True))
    op.drop_index('ix_rentals_message_date_desc', table_name='rentals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rentals_message_date_desc', 'rentals', [
                    sa.text('message_date DESC')], unique=False)
    op.drop_column('rentals', 'extra_expenses_details')
    op.drop_column('rentals', 'has_extra_expenses')
    # ### end Alembic commands ###
